// Source references use the manuscript's PRINTED page numbers, not PDF viewer indices.
const p=(...paragraphs)=>({type:'prose',paragraphs});
const sb=(key,why)=>({type:'scripture',key,why});
const reflect=(id,title,prompt)=>({type:'reflection',id,title,prompt});
const reveal=(title,text,label='Compare your thinking')=>({type:'reveal',title,text,label});
const note=(title,text,label='Course synthesis')=>({type:'note',title,text,label});
const deeper=(url,title,why)=>({type:'deeper',url,title,why});
const compare=(title,columns)=>({type:'compare',title,columns});
const step=(id,title,question,bridge,source,blocks)=>({id,title,question,bridge,source,blocks});
export const modules=[
{id:'start',title:'Start here',time:'6–10 min',thread:'Begin with your questions. Keep them open to the evidence.',outcome:'Know the purpose, choose a question, and understand the main path.',steps:[
step('welcome','A firm and functioning understanding.','What can this study help me understand?','First, make room for the questions you bring with you.','Preface; slides: mission and pre-class questions',[
p('The Holy Spirit’s role and work run from creation through the Christian today. This study follows that whole-Bible story so that familiar expressions can become more than familiar words.','Our aim is to understand what Scripture reveals, connect its testimony, and consider what that means for Christian life. We will also recognize the questions Scripture does not answer.'),
compare('Two ways to study here',[['Follow the main path','Read the short teaching, open the Scripture, and take time to think. Continue carries the argument forward. You can stop after any step.'],['Explore when you want','Deeper Study opens an optional SIS resource in a new tab. Close that tab to return here. These links are never prerequisites for the next step.']]),
note('Your pace, your place','Part One has five investigations with natural stopping points. Your place and reflections save on this browser when storage is available. No account, grades, or required written answers. You may think through a prompt without typing.','How this works')]),
step('baseline','What are you bringing to the study?','Which assumptions and questions should I keep in view?','With your starting point recorded, we can ask what makes this subject difficult.','Preface: pre-class questions 1, 3, 6',[
p('“I don’t know” is a useful starting point. These reflections expose your present understanding; they do not measure your worth or prepare a score. We will return to them before leaving Part One.'),
reflect('baseline-confusion','What is most confusing?','What stands in the way of your understanding of the Holy Spirit? Name one question you hope this study will clarify.'),
reflect('baseline-assumption','What do you currently believe?','What do you think people commonly get wrong about the Holy Spirit? What passage supports your own understanding?'),
reflect('baseline-filled','What does “filled with the Spirit” mean?','Give your best present explanation. If you are unsure, record what you would need to know before answering.')])]},
{id:'assumptions',title:'Make room for the evidence',time:'12–18 min',thread:'Our questions → our assumptions → the boundaries of a responsible answer',outcome:'Identify an assumption and distinguish an unanswered question from an unanswerable one.',steps:[
step('difficulty','Why does this feel difficult?','Is the difficulty in Scripture, or in what I bring to it?','One particularly influential assumption deserves a closer look.','Manuscript pp. 5–9',[
p('Several possible reasons help explain why this subject may be neglected: apparently limited evidence, confusing expressions, confidence that the matter is already settled, associations with the word “ghost,” and discomfort with unanswered questions. These are observations and possible explanations—not measured facts about every learner.','A word search may miss a passage that teaches about the Spirit without using the terminology we expected. Starting only in Acts can also hide the Old Testament background that makes later teaching intelligible.'),
sb('romans15','Read why earlier Scripture belongs in a Christian’s learning.'),
reflect('obstacle','Identify your own obstacle','Which of these possibilities fits you, if any? What would help you examine it rather than simply repeat it?'),
reveal('An association worth noticing','The manuscript wonders whether “ghost” language makes some people reluctant to study. Its discussion of occult practices and Deuteronomy 18:10–12 is background to that suggestion. It is not evidence that the Holy Spirit should be approached as an occult subject.','Optional source background')]),
step('settled','What if I think it is settled?','Does a familiar explanation account for everything the passage says?','A willingness to reconsider still needs a boundary: what has God actually revealed?','Manuscript pp. 6, 14, 19–20',[
p('This study directly challenges the claim that the Holy Spirit and God’s word are identical. We will test that claim through the actions Scripture attributes to Him. Start with Paul’s armor image.'),
sb('sword','Notice what Paul explicitly identifies as the word of God.'),
reflect('sword-observation','Read the relationship carefully','Paul identifies the sword as the word of God. Does that sentence identify the Spirit Himself as the sword? Explain the distinction in your own words.'),
reveal('What this observation establishes','The image distinguishes the Spirit from His sword. This distinction challenges treating “Holy Spirit” as merely another name for the written word. This is the opening of the argument; the prayer passages will add positive evidence about His work.'),
note('Keep the question alive','When we reach prayer, ask whether the action of interceding is an action of a person or simply another name for reading Scripture.','Carry forward')]),
step('boundaries','Curiosity needs a boundary.','What can I pursue confidently, and where should I stop?','With those boundaries in place, we can ask who the Holy Spirit is.','Manuscript pp. 7–9',[
sb('limits','Observe the distinction between what is secret and what is revealed.'),
p('We hold two commitments together: study what God has revealed diligently, and do not fill the gaps with imagination. “I have not found the answer yet” is different from “God has not revealed the answer.” Neither justifies pretending to know.','Another guardrail concerns terminology. A familiar religious label can collect meanings that the biblical passage never supplies. Be careful about turning ordinary words such as “gift” into a fixed category before reading their context.'),
reflect('boundary','Put the guardrail to work','Choose one question you have. What Scripture would you need to examine before deciding whether it can be answered?'),
reveal('Examples from the original discussion','The manuscript uses “antichrist,” “Sinner’s Prayer,” and capitalized “Grace” or “Gift” as examples of meanings being imposed on language. Their detailed arguments are not necessary here. The rule is: do not let a label settle what the passages must establish.','Optional source background'),
note('Before moving on','We have identified possible obstacles, opened a settled assumption to examination, and set a boundary around speculation. Recall one of those guardrails without rereading.','Pause & recall')])]},
{id:'godhead',title:'Know whom we are studying',time:'18–25 min',thread:'Guardrails → distinct persons and actions → one purpose',outcome:'Use a passage to distinguish Father, Son, and Spirit without dividing their purpose.',steps:[
step('three-present','Watch what each person does.','Where can I see the Father, Son, and Spirit together?','Now follow the same distinction from a visible event into Jesus’ words.','Manuscript pp. 10–11, 13–14',[
p('We have questioned whether the Spirit is merely another name for the word. The next step is to observe Scripture’s presentation of Him alongside the Father and Son. “Godhead” is the course’s shorthand for this divine relationship; the teaching does not depend on finding that English word.'),
sb('baptism','Look for the person baptized, the Spirit descending, and the voice from heaven.'),
{type:'matching',id:'baptism-roles',title:'Identify the actions',items:[['Jesus is baptized','Son'],['Descends like a dove','Spirit'],['Addresses Jesus as His beloved Son','Father']],options:['Father','Son','Spirit'],feedback:'The account presents distinct persons and actions in the same event. It does not describe three competing purposes.'},
note('Observe before illustrating','Mark describes the Spirit descending “like a dove.” That is the text. The source’s further connection between the dove and peace is an interpretation of the image. Keep those two kinds of statement distinct.','Text & interpretation')]),
step('another-helper','“Another Helper.”','What relationship does Jesus describe?','These distinct actions also appear in the apostles’ descriptions of salvation.','Manuscript pp. 10–11; John 14:16–17',[
sb('helper','Follow who asks, who gives, and who is given.'),
reflect('helper-roles','Explain the relationship','Who is speaking? Who is being asked? Who will come? How does this extend what you observed at Jesus’ baptism?'),
reveal('A relationship, not interchangeable names','Jesus asks the Father; the Father gives another Helper, the Spirit of truth. The immediate audience is Jesus’ apostles. Keep that audience in view before applying each promised activity to every Christian.'),
p('The Father, Son, and Spirit are distinct in this sentence while acting together for the disciples. That combination—distinction and unity—will remain important whenever we ask what the Spirit does.')]),
step('one-work','Distinct roles. One saving purpose.','How do the apostles describe their work together?','The language of this shared work also introduces a relationship: a household.','Manuscript pp. 11–13',[
sb('blessing','Notice what Paul associates with each person.'),
sb('peter','Compare Peter’s opening with Paul’s closing. Look for actions as well as names.'),
compare('Read the two passages together',[['Paul’s closing','The grace of the Lord Jesus Christ; the love of God; the fellowship of the Holy Spirit.'],['Peter’s opening','The foreknowledge of the Father; sanctification of the Spirit; obedience to Jesus Christ and sprinkling with His blood.']]),
reflect('unified-work','What is added by the second passage?','Describe something about the Spirit’s work that you could miss by looking only for the word “Godhead.”'),
note('Our conclusion so far','These passages present distinct divine persons, roles, and activities within one unified work. Listing an attribute beside one person is not a claim that the other persons lack that attribute.')]),
step('household','Why does God use family language?','What does an image help me understand about a spiritual relationship?','We now need a way to distinguish a helpful image from an interpretation we have supplied.','Manuscript pp. 12–15',[
p('“Father” brings a relationship into view. We will explore this through a father’s love and grief, then through images of a husband and a vineyard owner. These prepare the later investigation of God’s desire. Here, keep one image in view: His household.'),
sb('household','Identify the household, its cornerstone, and the Spirit’s role in the dwelling.'),
reflect('household-image','Explain the image','What does a household or a building help you understand here? What would be lost if you treated it as a description of literal construction materials?'),
reveal('Images prepare the larger story','The source’s father, husband, vineyard, shepherd, and king images describe relationships, responsibility, love, and response. The fuller Hosea 11, Isaiah 5, prodigal-son, and vineyard discussions belong with God’s Desire in Part Two. They have been deferred, not rejected.','Optional source background'),
deeper('https://scriptureinterpretsscripture.com/personality-of-the-godhead/','Where do we see the personality of the Godhead?','Explore the wider set of SIS passages showing the persons and their shared work.'),
note('Pause & recall','Name one passage that distinguishes the three persons. Then explain how it shows their work together. That evidence will keep the next investigation from becoming an abstract discussion of interpretation.','Module close')])]},
{id:'language',title:'Let Scripture control the answer',time:'18–25 min',thread:'Distinct persons → inspired language → warranted connections',outcome:'Distinguish an inspired explanation, a contextual connection, and speculation.',steps:[
step('whose-wisdom','Whose wisdom settles the question?','What should control our interpretation?','Paul explains why the Spirit’s revelation, rather than a teacher’s prestige, provides that foundation.','Manuscript pp. 15, 21–23; 1 Corinthians 1–4',[
p('We have used passages to identify the Godhead and a household image to understand their work. How do we keep our explanation accountable to those passages? Consider a church divided over teachers: Corinth.','Across 1 Corinthians 1–4, Paul addresses division and confidence in human wisdom. The subject of the Spirit appears inside that practical problem. It is not an isolated vocabulary exercise.'),
sb('wisdomPower','Ask where Paul says their faith should rest.'),
reflect('authority','Apply Paul’s contrast','When two explanations compete, what makes one trustworthy? Describe the difference between being impressed by a teacher and being persuaded by scriptural evidence.'),
reveal('A standard for this course too','The course’s own explanations must be judged by the Scripture they use. The manuscript makes Scripture the authority for resolving doctrine and conflict; neither credentials nor a persuasive style can replace that authority.')]),
step('revealed','The Spirit makes known.','How are the Spirit and the revealed message related?','That commitment to revealed language also sets a limit on our conclusions.','Manuscript pp. 21–22; 1 Corinthians 2:12–13; John 16:12–13',[
sb('revealed','Notice the source of what Paul and his fellow inspired messengers received.'),
p('We connect Paul’s explanation with Jesus’ promise to guide His apostles into truth. It treats the message delivered through those inspired witnesses as revelation from God. It does not use that promise to authorize a new revelation for each reader.','This returns us to the earlier distinction: the Spirit reveals God’s message, but the message does not exhaust everything Scripture says about the Spirit Himself.'),
reflect('revelation-distinction','Connect this to the sword','How can the word be the Spirit’s authoritative revelation without the Spirit and the written word being identical?'),
sb('written','Read Paul’s boundary in the context of division and boasting.')]),
step('connections','Who made the connection?','How much certainty does this interpretation deserve?','Try that distinction on a passage where the inspired writer supplies an explanation.','Slides: “Bible Standard for Interpretation”; manuscript pp. 7–8, 13–14',[
p('Distinguish direct interpretation, contextual reference, and conjecture or speculation. This tool will help us as we connect images and passages. It asks what warrants a connection; it does not assign a score to your faith.'),
{type:'standard',items:[['Direct interpretation','An inspired writer explains what is meant, identifies a fulfillment, or supplies the connection.'],['Contextual reference','An inspired writer uses related language or a figure, or records an event. Examine the context before equating passages.'],['Conjecture or speculation','A connection beyond what the text supplies must not be promoted into an inspired explanation.']]},
compare('Keep these voices distinct',[['Scripture and inspired explanation','The quotation belongs to the biblical text. When a writer explains its meaning within the text, that explanation has the same authority.'],['Course synthesis and inference','Our prose connects and explains passages. It remains accountable to them. An inference should be identified when it could be mistaken for an explicit statement.']]),
reflect('certainty-test','Test an explanation','Think of a claim you have heard about the Spirit. Did an inspired writer make that connection, or did the teacher make it? What would you examine next?')]),
step('john-explains','John tells us what Jesus meant.','What is explicit, and what still needs investigation?','John has linked the Spirit’s coming with Jesus’ glorification. That gives us the next question: what changes when Jesus departs?','Manuscript p. 16; slides: interpretive certainty and John thread',[
sb('living','Read Jesus’ words and then John’s explanation in verse 39.'),
{type:'classify',id:'connection-check',title:'Identify the warrant',items:[['John says Jesus was speaking about the Spirit.','Direct interpretation'],['This image must refer to one particular Old Testament passage, even without evidence.','Conjecture or speculation'],['We compare “living water” language across passages while examining their contexts.','Contextual reference']],options:['Direct interpretation','Contextual reference','Conjecture or speculation'],feedback:'John explicitly identifies the Spirit. Finding an Old Testament background requires further contextual work. An unsupported choice of one passage is not an inspired identification.'},
note('What we can carry forward','John connects the promised reception of the Spirit with Jesus’ glorification. We do not need to invent that connection. The fuller “living water” investigation belongs later in the study.','Inspired connection'),
note('Natural stopping point','We now have a method: read in context, compare Scripture, identify who supplies the connection, and stop where revelation stops. In the next investigation we use that method to trace a change in emphasis across the Bible.','Module close')])]},
{id:'age',title:'Trace the change in emphasis',time:'15–22 min',thread:'The whole Bible → the Son’s departure → the Helper’s coming',outcome:'Explain “Spirit Age” as a course framework without implying the Spirit was previously absent.',steps:[
step('whole-story','A whole-Bible subject.','What do we mean by a “Spirit Age”?','The framework is useful only if Jesus’ own words support the change it describes.','Manuscript p. 16; slides: segmenting the Bible',[
p('We use “Father age,” “Son age,” and “Spirit age” to describe a change in emphasis across the biblical story. These are course labels, not a claim that only one person of the Godhead existed or acted during each period.','The Old Testament foregrounds the Father; the Gospels foreground the Son’s earthly ministry; Acts through Revelation foreground the Spirit’s work in the establishment and life of the church. This reading framework does not replace the Bible’s covenants or imply three separate gods.'),
{type:'timeline',items:[['Old Testament','The Father’s desire and promises','The Son and Spirit are not absent. The earlier story supplies the background for what follows.'],['Gospels','The Son comes and accomplishes His work','At His baptism we have already seen Father, Son, and Spirit acting together.'],['Acts–Revelation','The Helper and the church','The Father and Son continue to act. The focus follows the promised coming and work of the Spirit.']]},
reflect('age-correction','Correct the misunderstanding','Someone says, “The Spirit Age means the Spirit first became active after Jesus left.” Use something we have already read to explain why that is mistaken.')]),
step('departure','Why is His departure an advantage?','What does Jesus say will follow His going away?','The promised Helper belongs to the work Jesus accomplishes—not to a disconnected second story.','Manuscript pp. 16–18; John 16:7',[
sb('departure','Listen for the relationship Jesus states between His departure and the Helper’s coming.'),
sb('helper','Return to the Father, Son, and Helper in the upper-room promise.'),
reflect('departure-predict','Make the connection','Why would returning to the Father, Son, and Spirit help us understand this promise better than treating the Helper as an isolated topic?'),
reveal('The story continues','The Son’s departure prepares the coming of the Helper whom He will send. We call this a change of emphasis within the unified work of the Godhead. It does not mean the Son ceases to be Lord or the Father withdraws.'),
note('Remember the audience','Jesus is addressing His apostles before His death. We will trace how their work relates to the church instead of assuming every detail of their commission applies identically to every believer.','Context matters')]),
step('curtain','A new and living way.','How does Jesus’ death open access to God?','Access and dwelling now give substance to the Spirit expressions we encounter in the letters.','Manuscript pp. 17–18',[
p('At Jesus’ death, Matthew records the temple curtain being torn from top to bottom. We place that event beside Hebrews’ description of the way opened through Jesus. This connects the Spirit study with the death of Christ and access to God.'),
sb('curtain','Begin with the event Matthew records.'),
sb('access','Then observe the connection Hebrews explicitly makes between the curtain and Jesus’ flesh.'),
reflect('access-connect','Explain what changed','What gives the readers of Hebrews confidence to draw near? Why does the earlier temple background matter to that explanation?'),
note('Distinguish the levels','Hebrews explicitly connects the curtain with Jesus’ flesh. Describing the torn curtain as an image of the transition into the “Spirit Age” is the course’s synthesis of these passages.','Course synthesis'),
reveal('The other events at Calvary','The manuscript also discusses darkness, the earthquake, and the saints raised after Jesus’ resurrection. Those details remain in the source’s Matthew 27 discussion. Here the curtain carries the immediate argument about access.','Optional source background')]),
step('phrase-map','Familiar phrases become questions.','What should I investigate before fixing their meanings?','We will try the method on one expression now: praying in the Spirit.','Manuscript pp. 18–19, 24; Holy Spirit Key',[
p('Scripture uses expressions such as baptized with the Spirit, filled with the Spirit, led by the Spirit, dwelling by the Spirit, grieving the Spirit, and praying in the Spirit. Their recurrence is an invitation to compare contexts, not a reason to assume they all mean the same thing.'),
{type:'phrases',items:[['Filled with the Spirit','Ephesians 5:18','Who is instructed, and what kind of life surrounds the instruction?'],['Led by the Spirit','Romans 8:13–14','How does the surrounding passage connect the Spirit with putting sin to death?'],['A dwelling by the Spirit','Ephesians 2:19–22','Who is being built together, and what does the household image add?'],['Praying in the Spirit','Ephesians 6:18; Jude 19–21','How do these contexts qualify the meaning?']]},
reflect('phrase-question','Choose a question to carry forward','Which expression stands out to you? Write a question that requires more than substituting a familiar definition.'),
note('What we have established','“Spirit Age” describes a change in emphasis, not the absence of the Father or Son. The Helper’s coming belongs to the work Jesus accomplishes. The remaining expressions must be read within this whole-Bible story.','Module close')])]},
{id:'prayer',title:'Put the guardrails to work',time:'20–28 min',thread:'One phrase → several witnesses → a bounded conclusion → four anchors',outcome:'Explain the prayer case study with evidence and identify why the course next returns to the Old Testament.',steps:[
step('prayer-predict','What is “praying in the Spirit”?','What might the expression mean before we compare passages?','Hold your first explanation beside Jude’s contrast.','Manuscript pp. 19–20',[
p('We have met the persons of the Godhead, established the authority of Scripture, and traced the Helper’s coming. Now those ideas work together on a practical question. Before reading the comparison, give your present explanation.'),
reflect('prayer-before','Make a prediction','What would you understand “praying in the Spirit” to involve? What might you expect the next passage to confirm or correct?'),
sb('sword','Read the prayer instruction alongside the Spirit’s sword.'),
p('Be careful about immediately equating this expression with tongues or new revelation. Instead of settling the question from an association, we will compare what the biblical writers actually say.')]),
step('jude-contrast','Jude gives us a contrast.','What does the context begin to exclude?','Jude places prayer within faithful fellowship. Paul next adds an action of the Spirit Himself.','Manuscript pp. 19–21',[
sb('jude','Contrast those devoid of the Spirit with the instruction to the beloved.'),
compare('Notice the contrast',[['Those causing division','Worldly people, devoid of the Spirit.'],['The beloved','Build yourselves up in faith, pray in the Holy Spirit, keep yourselves in God’s love, and wait for Christ’s mercy.']]),
reflect('jude-revise','Revise your prediction','What does Jude add to your first explanation? What interpretation would fail to account for this contrast?'),
note('What the source infers','The manuscript infers that praying in the Spirit belongs to faithful fellowship with God rather than following ungodly passions. Jude supplies the contrast; the statement about fellowship is the source’s synthesis. This passage is not yet the whole account.','Interpretive inference')]),
step('spirit-helps','The Spirit Himself helps.','What does Paul add that Jude has not yet explained?','Now connect this help with the Father and Son in prayer.','Manuscript p. 20; Romans 8:26–27',[
sb('romans8','Identify the helper, the weakness, and the action of interceding.'),
reflect('help-boundary','Say what is revealed—and stop there','What does Paul tell us the Spirit does? What question about how He does it remains unexplained?'),
reveal('Help without an invented mechanism','The Spirit helps in weakness and intercedes according to God’s will. This study affirms His personal contribution to Christian prayer. It does not claim to explain the mechanism or turn the passage into a promise of additional revelation.'),
p('Return to our early question about the Spirit and His sword. Scripture is indispensable to knowing God’s will; Paul also describes the Spirit Himself acting for the saints. The course’s argument asks us to account for both rather than erase one.')]),
step('prayer-together','In the Spirit. To the Father. Through the Son.','How do the passages contribute to one understanding of prayer?','This is a practical example of the larger story: God bringing His people into fellowship.','Manuscript pp. 20–21',[
sb('prayerSon','Notice to whom Jesus directs prayer and in whose name.'),
{type:'matching',id:'prayer-roles',title:'Bring the witnesses together',items:[['Prayer is directed to Him','Father'],['Prayer is offered in His name','Son'],['Helps in weakness and intercedes','Spirit']],options:['Father','Son','Spirit'],feedback:'Combining John 16:23 with Romans 8:26–27 and Jude 19–21 gives us this synthesis: to the Father, through the Son, in the Spirit. This is a synthesis of the passages, not a single quoted formula.'},
reflect('prayer-application','From explanation to practice','A Christian says, “If I cannot find the right words, my prayer must be useless.” How would you respond from Romans 8 without promising a revelation the passage does not promise?'),
reveal('A response grounded in the passage','Paul acknowledges weakness and describes the Spirit’s help. Confidence can rest in that revealed help without pretending to know how the intercession works. The source couples this assurance with Jude’s call to remain in God’s love.'),
{type:'deeperFrom',key:'jude',match:'pray in the Spirit',why:'Explore SIS’s fuller treatment of the same question. The necessary comparison is already here.'}]),
step('church-life','The guardrails matter in a congregation.','How does this affect more than my definitions?','Prayer and shared holiness lead us back to the purpose running through the whole study.','Manuscript pp. 21–23',[
sb('temple','Read the Spirit’s dwelling in the context of a divided church.'),
p('We return to Corinth to show why these questions matter. A people described as God’s temple cannot treat division as though it has nothing to do with the Spirit. Their shared life must be governed by God’s revealed word.','The source later connects the collective temple with the individual Christian’s responsibility. We are not completing the dwelling investigation here; we are seeing why it is necessary.'),
reflect('congregation-application','Apply the standard','If a congregation divides around preferred teachers, how do Paul’s warning about the temple and his rejection of boasting challenge that response?'),
note('Where we are','Our study has moved from identifying the Spirit to observing His work and considering the faithful life that follows. The next stage asks why God desired this relationship and how He promised it.','Synthesis')]),
step('anchors','Four anchors for the journey ahead.','Why must we now return to the earlier story?','Before leaving Part One, revisit the questions you brought into it.','Manuscript p. 23; slides: Desire / Promise / Dwelling / Power',[
p('We organize the continuing investigation around four connected anchors. These are a map of what comes next, not four new doctrines established by a diagram.'),
{type:'anchors',items:[['Desire','God’s desire for a loving relationship with those He created.','Why does God seek to dwell with His people?'],['Promise','The Father’s promise against the backdrop of sin, Law, and prophets.','What did God promise, and to whom?'],['Dwelling','God’s dwelling with His people in the work of the Spirit.','How is the promised relationship realized?'],['Power','God’s power making that relationship possible and shaping life by the Spirit.','What does the Spirit enable, then and today?']]},
p('Part Two returns to the Law and Prophets because the later statements grow out of that history. We are not leaving the Holy Spirit behind when we ask about the Father’s desire or the promises He made. We are learning the background needed to understand His work.'),
reflect('anchors-recall','Build the connection yourself','Explain why reading only “Spirit” passages in Acts and the letters could leave important questions unanswered. Connect at least two anchors in your response.')]),
step('return','What do you see differently now?','What has changed, and what still needs the rest of the study?','Part One ends here. The next investigation will begin with God’s Desire.','Preface reflections revisited; manuscript pp. 23–24',[
{type:'revisit',ids:['baseline-confusion','baseline-assumption','baseline-filled']},
reflect('after-groundwork','Compare your thinking','Which earlier assumption changed? Which passage caused that change? Which question is still open? You do not need to have settled “filled with the Spirit” yet.'),
note('Prepared to continue','You have practiced reading the Spirit in relation to the Father and Son, distinguishing evidence from inference, and comparing passages without inventing answers. Those are the tools the later promise, dwelling, and power investigations require.','Part One close'),
p('Part Two is not yet built in this prototype. The original God’s Promise experience remains available for comparison. Part One supplies groundwork, but the Law and Prophets material still stands between this point and that later investigation.'),
{type:'finish'}])]}];
export const steps=modules.flatMap((m,moduleIndex)=>m.steps.map((s,withinModule)=>({...s,moduleIndex,withinModule})));
export const reflectionPrompts=Object.fromEntries(steps.flatMap(s=>s.blocks.filter(b=>b.type==='reflection').map(b=>[b.id,b.title])));
